version: '3.4'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3306:3306
    volumes:
      - blogdata:/var/lib/mysql
      - /root/docker/mysql-latest/conf.d:/etc/mysql/conf.d
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mysql
    ports:
      - 8081:8080
volumes:
  blogdata:
